FROM oven/bun:1

USER 1000:1000

WORKDIR /app

COPY drizzle.config.ts .
COPY server/database server/database
COPY package.migrations.json package.json

CMD ["sh", "-c", "bun install && bun run drizzle-kit migrate"]
