FROM oven/bun:1

WORKDIR /app

USER 1000:1000

COPY drizzle.config.ts .
COPY server/database server/database
COPY package.migrations.json package.json

COMMAND ["sh", "-c", "bun install && bun run drizzle-kit migrate"]
